# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of the node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See the supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: ''
    - run: npm install yarn
    - run: yarn install
    - run: install -g @angular/cli
    - run: sudo apt-get install sshpass
    - run: ng build --prod

    - name: Upload Files
      uses: siva1024/scp-deployer@latest
      with:
        host: 203.190.146.204
        username: vinod
        password: pp
        port: 112
        source: "./build/*"
        target: "/var/www/html/vijay-test"
